CGLVector3D
double CGLVector3D::x
Referenced by CGLColor::set, CGLColor::setR, CGLColor::getR, CGLColor::drawObject, CGLPosition::drawObject, CGLRotation::set, CGLRotation::drawObject, CGLScale::drawObject, CGLVector3D, getX, set, setX, isEqualTo, CGLVector4D::set.
double CGLVector3D::y
Referenced by CGLColor::set, CGLColor::setG, CGLColor::getG, CGLColor::drawObject, CGLPosition::drawObject, CGLRotation::set, CGLRotation::drawObject, CGLScale::drawObject, CGLVector3D, getY, set, setY, isEqualTo, CGLVector4D::set.
double CGLVector3D::z
Referenced by CGLColor::set, CGLColor::setB, CGLColor::getB, CGLColor::drawObject, CGLPosition::drawObject, CGLRotation::set, CGLRotation::drawObject, CGLScale::drawObject, CGLVector3D, getZ, set, setZ, isEqualTo, CGLVector4D::set.
CGLVector3D::CGLVector3D()
References x, y, z.
CGLVector3D::~CGLVector3D()
bool CGLVector3D::isEqualTo(CGLVector3D const &b) const
References x, getX, y, getY, z, getZ.
Referenced by operator==.
double const & CGLVector3D::getX() const
References x.
Referenced by CGLLine::drawObject, isEqualTo.
double const & CGLVector3D::getY() const
References y.
Referenced by CGLLine::drawObject, isEqualTo.
double const & CGLVector3D::getZ() const
References z.
Referenced by CGLLine::drawObject, isEqualTo.
void CGLVector3D::set(double const &xv, double const &yv, double const &zv)
References x, y, z.
Referenced by CGLLine::CGLLine, main.
void CGLVector3D::setX(double const &val)
References x.
void CGLVector3D::setY(double const &val)
References y.
void CGLVector3D::setZ(double const &val)
References z.