CGLVector2D
double CGLVector2D::maxX
Referenced by getMaxX, setX, setMaxX, isXMax.
double CGLVector2D::maxY
Referenced by getMaxY, setY, setMaxY, isYMax.
double CGLVector2D::minX
Referenced by getMinX, setX, setMinX, isXMin.
double CGLVector2D::minY
Referenced by getMinY, setY, setMinY, isYMin.
double CGLVector2D::x
Referenced by CGLColor::set, CGLColor::setR, CGLColor::getR, CGLColor::drawObject, CGLPosition::drawObject, CGLPositionSpeed::drawObject, CGLRotation::set, CGLRotation::drawObject, CGLRotationSpeed::drawObject, CGLScale::drawObject, getX, set, setX, setMinX, setMaxX, normalize, isXMin, isXMax, CGLVector3D::set, CGLVector3D::isEqualTo, CGLVector4D::set.
double CGLVector2D::y
Referenced by CGLColor::set, CGLColor::setG, CGLColor::getG, CGLColor::drawObject, CGLPosition::drawObject, CGLPositionSpeed::drawObject, CGLRotation::set, CGLRotation::drawObject, CGLRotationSpeed::drawObject, CGLScale::drawObject, getY, set, setY, setMinY, setMaxY, normalize, isYMin, isYMax, CGLVector3D::set, CGLVector3D::isEqualTo, CGLVector4D::set.
CGLVector2D::CGLVector2D()
CGLVector2D::~CGLVector2D()
double const & CGLVector2D::getMaxX() const
References maxX.
double const & CGLVector2D::getMaxY() const
References maxY.
double const & CGLVector2D::getMinX() const
References minX.
double const & CGLVector2D::getMinY() const
References minY.
double const & CGLVector2D::getX() const
References x.
Referenced by CGLLine::drawObject, CGLPositionSpeed::drawObject, CGLVector3D::isEqualTo.
double const & CGLVector2D::getY() const
References y.
Referenced by CGLLine::drawObject, CGLPositionSpeed::drawObject, CGLVector3D::isEqualTo.
bool CGLVector2D::isXMax() const
References x, maxX.
Referenced by CGLPositionSpeed::drawObject.
bool CGLVector2D::isYMax() const
References y, maxY.
Referenced by CGLPositionSpeed::drawObject.
bool CGLVector2D::isXMin() const
References x, minX.
Referenced by CGLPositionSpeed::drawObject.
bool CGLVector2D::isYMin() const
References y, minY.
Referenced by CGLPositionSpeed::drawObject.
void CGLVector2D::normalize()
References x, y.
void CGLVector2D::set(double const &valx, double const &valy)
References setX, x, setY, y.
Referenced by CGLQuad::CGLQuad, CGLTriangle::CGLTriangle.
void CGLVector2D::setMaxX(double const &val)
References x, maxX.
Referenced by main.
void CGLVector2D::setMaxY(double const &val)
References y, maxY.
Referenced by main.
void CGLVector2D::setMinX(double const &val)
References x, minX.
Referenced by main.
void CGLVector2D::setMinY(double const &val)
References y, minY.
Referenced by main.
void CGLVector2D::setX(double const &val)
References maxX, x, minX.
Referenced by CGLPositionSpeed::CGLPositionSpeed, CGLPositionSpeed::drawObject, set.
void CGLVector2D::setY(double const &val)
References maxY, y, minY.
Referenced by CGLPositionSpeed::drawObject, set.