CGLObject
int CGLObject::objectType
Referenced by CGLBoite::CGLBoite, CGLCamera::CGLCamera, CGLObject, CGLScene::CGLScene, CGLWindow::CGLWindow, CGLWorld::CGLWorld.
string CGLObject::name
Referenced by CGLCamera::CGLCamera, CGLObject, setName, getName, CGLScene::CGLScene, CGLWindow::CGLWindow, CGLWorld::CGLWorld.
bool CGLObject::matrixSaved
Referenced by CGLEffect::CGLEffect, CGLItem::CGLItem, CGLObject, draw, CGLScene::CGLScene, CGLSpecial::CGLSpecial, CGLWorld::CGLWorld.
list<CGLObject *> CGLObject::children
Referenced by addObject, drawChildren, isChild.
list<CGLObject *>::iterator CGLObject::iterCurrentObject
Referenced by addObject.
CGLObject* CGLObject::currentObject
Referenced by CGLCameraList::getCurrentCamera, CGLObject, addObject, getCurrentObject, CGLWindow::getCurrentWorld, CGLWorld::draw, CGLWorld::getCurrentScene.
CGLObject* CGLObject::parentObject
Referenced by CGLObject.
CGLObject * CGLObject::garbage
Referenced by addObject.
void CGLObject::addObject(CGLObject *object)
References children, iterCurrentObject, currentObject, garbage, isChild, addObject.
Referenced by CGLObject, addObject, CGLScene::CGLScene, CGLScene::addCamera, CGLScene::addItem, CGLWindow::CGLWindow, CGLWorld::CGLWorld, main.
void CGLObject::setName(string n)
References name.
Referenced by CGLScene::CGLScene, main.
string CGLObject::getName()
References name.
CGLObject * CGLObject::getCurrentObject()
References currentObject.
Referenced by CGLScene::draw, CGLScene::getCurrentCamera.
bool CGLObject::isChild(CGLObject *obj)
References children.
Referenced by addObject.
void CGLObject::draw(Uint32 timeEllapsed)
References matrixSaved, drawChildren, drawObject.
Referenced by CGLRobot1::drawObject, CGLScene::draw.
void CGLObject::drawObject(Uint32 timeEllapsed)
Referenced by draw.
void CGLObject::drawChildren(Uint32 timeEllapsed)
References children.
Referenced by draw, CGLScene::draw.
void CGLObject::drawCenter()
CGLObject::CGLObject()
Prépare tout pour vous…
References objectType, name, matrixSaved, parentObject, currentObject, addObject.
Referenced by init, CGLScene::CGLScene.
CGLObject::~CGLObject()
void CGLObject::init()
References CGLObject.
Referenced by main.