CGLWindow
bool CGLWindow::active
bool CGLWindow::animation
SDL_Event CGLWindow::ev
SDL_Surface* CGLWindow::ecran
Uint32 CGLWindow::startTime
Uint32 CGLWindow::lastTime
Uint32 CGLWindow::currentTime
Uint32 CGLWindow::ellapsedTime
CGLWindow::CGLWindow()
References CGLObject::objectType, CGLObject::name, CGLObject::addObject.
CGLWindow::~CGLWindow()
void CGLWindow::loop()
References getCurrentWorld, CGLWorld::getCurrentScene, CGLScene::getCurrentCamera, CGLCamera::onMouseButton, onResize, draw.
Referenced by exec.
void CGLWindow::exec()
References loop.
Referenced by main.
void CGLWindow::onResize(SDL_Event &ev)
Referenced by loop.
void CGLWindow::draw(Uint32 ellapsedTime)
References getCurrentWorld, CGLWorld::draw.
Referenced by loop.
CGLWorld * CGLWindow::getCurrentWorld()
References CGLObject::currentObject.
Referenced by loop, draw, main.