CGLWorld
list<CGLObject*>::iterator CGLWorld::currentScene
CGLWorld::CGLWorld()
References CGLObject::objectType, CGLObject::name, CGLObject::matrixSaved, CGLObject::addObject.
CGLWorld::~CGLWorld()
void CGLWorld::draw(Uint32 timeEllapsed)
References CGLObject::currentObject.
Referenced by CGLWindow::draw.
CGLScene * CGLWorld::getCurrentScene()
References CGLObject::currentObject.
Referenced by CGLWindow::loop, main.