.TH "Répertoire de référence de /home/dagal/git/DamierGL/DamierGL/src" 3 "Jeudi 6 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de /home/dagal/git/DamierGL/DamierGL/src \- 
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBCGL\fP"
.br
.in -1c
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBDamierGL\&.cpp\fP"
.br
.in -1c
