.TH "CGLBoite" 3 "Vendredi 28 Février 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLBoite \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLBoite\&.h>\fP
.PP
Est dérivée de \fBCGLItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLBoite\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLBoite\fP ()"
.br
.ti -1c
.RI "void \fBsetTaille\fP (double, double, double)"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 timeEllapsed)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 13 du fichier CGLBoite\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLBoite::CGLBoite ()"

.PP
Définition à la ligne 10 du fichier CGLBoite\&.cpp\&.
.SS "CGLBoite::~CGLBoite ()\fC [virtual]\fP"

.PP
Définition à la ligne 16 du fichier CGLBoite\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLBoite::drawObject (Uint32timeEllapsed)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 26 du fichier CGLBoite\&.cpp\&.
.SS "void CGLBoite::setTaille (doublexv, doubleyv, doublezv)"

.PP
Définition à la ligne 19 du fichier CGLBoite\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
