.TH "/home/dagal/git/DamierGL/DamierGL/src/CGL/CGLCircle.h" 3 "Jeudi 6 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dagal/git/DamierGL/DamierGL/src/CGL/CGLCircle.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CGLItem\&.h'\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCGLCircle\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBPI\fP = 3\&.141592653589793238463"
.br
.in -1c
.SH "Documentation des variables"
.PP 
.SS "const double PI = 3\&.141592653589793238463"

.PP
Définition à la ligne 13 du fichier CGLCircle\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
