.TH "CGLColor" 3 "Samedi 1 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLColor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLColor\&.h>\fP
.PP
Est dérivée de \fBCGLEffect\fP, et \fBCGLVector4D\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLColor\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLColor\fP ()"
.br
.ti -1c
.RI "void \fBset\fP (double rv, double gv, double bv, double av)"
.br
.ti -1c
.RI "void \fBsetR\fP (double rv)"
.br
.ti -1c
.RI "void \fBsetG\fP (double gv)"
.br
.ti -1c
.RI "void \fBsetB\fP (double bv)"
.br
.ti -1c
.RI "void \fBsetA\fP (double av)"
.br
.ti -1c
.RI "double \fBgetR\fP ()"
.br
.ti -1c
.RI "double \fBgetG\fP ()"
.br
.ti -1c
.RI "double \fBgetB\fP ()"
.br
.ti -1c
.RI "double \fBgetA\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 timeEllapsed)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 17 du fichier CGLColor\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLColor::CGLColor ()"

.PP
Définition à la ligne 13 du fichier CGLColor\&.cpp\&.
.SS "CGLColor::~CGLColor ()\fC [virtual]\fP"

.PP
Définition à la ligne 17 du fichier CGLColor\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLColor::drawObject (Uint32timeEllapsed)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 69 du fichier CGLColor\&.cpp\&.
.SS "double CGLColor::getA ()"

.PP
Définition à la ligne 64 du fichier CGLColor\&.cpp\&.
.SS "double CGLColor::getB ()"

.PP
Définition à la ligne 59 du fichier CGLColor\&.cpp\&.
.SS "double CGLColor::getG ()"

.PP
Définition à la ligne 54 du fichier CGLColor\&.cpp\&.
.SS "double CGLColor::getR ()"

.PP
Définition à la ligne 49 du fichier CGLColor\&.cpp\&.
.SS "void CGLColor::set (doublerv, doublegv, doublebv, doubleav)"

.PP
Définition à la ligne 21 du fichier CGLColor\&.cpp\&.
.SS "void CGLColor::setA (doubleav)"

.PP
Définition à la ligne 44 du fichier CGLColor\&.cpp\&.
.SS "void CGLColor::setB (doublebv)"

.PP
Définition à la ligne 39 du fichier CGLColor\&.cpp\&.
.SS "void CGLColor::setG (doublegv)"

.PP
Définition à la ligne 34 du fichier CGLColor\&.cpp\&.
.SS "void CGLColor::setR (doublerv)"

.PP
Définition à la ligne 29 du fichier CGLColor\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
