.TH "CGLCircle" 3 "Jeudi 6 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLCircle \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLCircle\&.h>\fP
.PP
Est dérivée de \fBCGLItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLCircle\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLCircle\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "int \fBnbc\fP"
.br
.ti -1c
.RI "double \fBradius\fP"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 19 du fichier CGLCircle\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLCircle::CGLCircle ()"

.PP
Définition à la ligne 10 du fichier CGLCircle\&.cpp\&.
.SS "CGLCircle::~CGLCircle ()\fC [virtual]\fP"

.PP
Définition à la ligne 14 du fichier CGLCircle\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLCircle::drawObject (Uint32ellapsedTime)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 18 du fichier CGLCircle\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "int CGLCircle::nbc\fC [protected]\fP"

.PP
Définition à la ligne 22 du fichier CGLCircle\&.h\&.
.SS "double CGLCircle::radius\fC [protected]\fP"

.PP
Définition à la ligne 23 du fichier CGLCircle\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
