.TH "CGLCameraList" 3 "Samedi 1 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLCameraList \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLCameraList\&.h>\fP
.PP
Est dérivée de \fBCGLSpecial\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLCameraList\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLCameraList\fP ()"
.br
.ti -1c
.RI "\fBCGLCamera\fP * \fBgetCurrentCamera\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 16 du fichier CGLCameraList\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLCameraList::CGLCameraList ()"

.PP
Définition à la ligne 10 du fichier CGLCameraList\&.cpp\&.
.SS "CGLCameraList::~CGLCameraList ()\fC [virtual]\fP"

.PP
Définition à la ligne 14 du fichier CGLCameraList\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBCGLCamera\fP * CGLCameraList::getCurrentCamera ()"

.PP
Définition à la ligne 18 du fichier CGLCameraList\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
