.TH "CGLDot" 3 "Jeudi 6 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLDot \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLDot\&.h>\fP
.PP
Est dérivée de \fBCGLItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLDot\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLDot\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 16 du fichier CGLDot\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLDot::CGLDot ()"

.PP
Définition à la ligne 10 du fichier CGLDot\&.cpp\&.
.SS "CGLDot::~CGLDot ()\fC [virtual]\fP"

.PP
Définition à la ligne 14 du fichier CGLDot\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLDot::drawObject (Uint32ellapsedTime)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 18 du fichier CGLDot\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
