.TH "CGLDot" 3 "Lundi 14 Avril 2014" "Version 20140414" "DGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLDot \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dot\&.h>\fP
.PP
Est dérivée de CGLItem\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLDot\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLDot\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 16 du fichier Dot\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLDot::CGLDot ()"

.PP
Définition à la ligne 10 du fichier Dot\&.cpp\&.
.SS "CGLDot::~CGLDot ()\fC [virtual]\fP"

.PP
Définition à la ligne 14 du fichier Dot\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLDot::drawObject (Uint32ellapsedTime)"

.PP
Définition à la ligne 18 du fichier Dot\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DGL à partir du code source\&.
