.TH "/home/dagal/git/DamierGL/DamierGL/src/CGL/CGLEffect.h" 3 "Lundi 3 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dagal/git/DamierGL/DamierGL/src/CGL/CGLEffect.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CGLObject\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCGLEffect\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
