.TH "CGLEffect" 3 "Samedi 1 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLEffect \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLEffect\&.h>\fP
.PP
Est dérivée de \fBCGLObject\fP\&.
.PP
Dérivée par \fBCGLColor\fP, \fBCGLPosition\fP, \fBCGLRotation\fP, et \fBCGLScale\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLEffect\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLEffect\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 16 du fichier CGLEffect\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLEffect::CGLEffect ()"

.PP
Définition à la ligne 10 du fichier CGLEffect\&.cpp\&.
.SS "CGLEffect::~CGLEffect ()\fC [virtual]\fP"

.PP
Définition à la ligne 15 du fichier CGLEffect\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
