.TH "CGLItem" 3 "Jeudi 6 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLItem \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLItem\&.h>\fP
.PP
Est dérivée de \fBCGLObject\fP\&.
.PP
Dérivée par \fBCGLBoite\fP, \fBCGLCircle\fP, \fBCGLDot\fP, \fBCGLLine\fP, \fBCGLPolygon\fP, \fBCGLQuad\fP, \fBCGLRobot1\fP, et \fBCGLTriangle\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLItem\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLItem\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 17 du fichier CGLItem\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLItem::CGLItem ()"

.PP
Définition à la ligne 10 du fichier CGLItem\&.cpp\&.
.SS "CGLItem::~CGLItem ()\fC [virtual]\fP"

.PP
Définition à la ligne 15 du fichier CGLItem\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
