.TH "/home/dagal/git/DamierGL/DamierGL/src/CGL/CGLLine.h" 3 "Vendredi 28 Février 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dagal/git/DamierGL/DamierGL/src/CGL/CGLLine.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CGLItem\&.h'\fP
.br
\fC#include 'CGLVector3D\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCGLLine\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
