.TH "CGLLine" 3 "Lundi 14 Avril 2014" "Version 20140414" "DGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLLine \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Line\&.h>\fP
.PP
Est dérivée de CGLItem\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLLine\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLLine\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "CGLVector3D \fBendPoint\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 17 du fichier Line\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLLine::CGLLine ()"

.PP
Définition à la ligne 10 du fichier Line\&.cpp\&.
.SS "CGLLine::~CGLLine ()\fC [virtual]\fP"

.PP
Définition à la ligne 15 du fichier Line\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLLine::drawObject (Uint32ellapsedTime)"

.PP
Définition à la ligne 19 du fichier Line\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "CGLVector3D CGLLine::endPoint\fC [protected]\fP"

.PP
Définition à la ligne 20 du fichier Line\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DGL à partir du code source\&.
