.TH "CGLLight" 3 "Samedi 1 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLLight \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLLight\&.h>\fP
.PP
Est dérivée de \fBCGLSpecial\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLLight\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLLight\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 13 du fichier CGLLight\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLLight::CGLLight ()"

.PP
Définition à la ligne 10 du fichier CGLLight\&.cpp\&.
.SS "CGLLight::~CGLLight ()\fC [virtual]\fP"

.PP
Définition à la ligne 14 du fichier CGLLight\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
