.TH "CGLLine" 3 "Samedi 1 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLLine \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLLine\&.h>\fP
.PP
Est dérivée de \fBCGLItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLLine\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLLine\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBCGLVector3D\fP \fBendPoint\fP"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 17 du fichier CGLLine\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLLine::CGLLine ()"

.PP
Définition à la ligne 10 du fichier CGLLine\&.cpp\&.
.SS "CGLLine::~CGLLine ()\fC [virtual]\fP"

.PP
Définition à la ligne 15 du fichier CGLLine\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLLine::drawObject (Uint32ellapsedTime)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 19 du fichier CGLLine\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBCGLVector3D\fP CGLLine::endPoint\fC [protected]\fP"

.PP
Définition à la ligne 20 du fichier CGLLine\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
