.TH "CGLPositionSpeed" 3 "Lundi 3 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLPositionSpeed \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLPositionSpeed\&.h>\fP
.PP
Est dérivée de \fBCGLPosition\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLPositionSpeed\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLPositionSpeed\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBCGLVector3D\fP \fBspeed\fP"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 17 du fichier CGLPositionSpeed\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLPositionSpeed::CGLPositionSpeed ()"

.PP
Définition à la ligne 10 du fichier CGLPositionSpeed\&.cpp\&.
.SS "CGLPositionSpeed::~CGLPositionSpeed ()\fC [virtual]\fP"

.PP
Définition à la ligne 15 du fichier CGLPositionSpeed\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLPositionSpeed::drawObject (Uint32ellapsedTime)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLPosition\fP\&.
.PP
Définition à la ligne 19 du fichier CGLPositionSpeed\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBCGLVector3D\fP CGLPositionSpeed::speed\fC [protected]\fP"

.PP
Définition à la ligne 20 du fichier CGLPositionSpeed\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
