.TH "CGLPolygon" 3 "Jeudi 6 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLPolygon \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLPolygon\&.h>\fP
.PP
Est dérivée de \fBCGLItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLPolygon\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLPolygon\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "list< \fBCGLVector2D\fP * > \fBpoints\fP"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 20 du fichier CGLPolygon\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLPolygon::CGLPolygon ()"

.PP
Définition à la ligne 10 du fichier CGLPolygon\&.cpp\&.
.SS "CGLPolygon::~CGLPolygon ()\fC [virtual]\fP"

.PP
Définition à la ligne 24 du fichier CGLPolygon\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLPolygon::drawObject (Uint32ellapsedTime)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 29 du fichier CGLPolygon\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "list<\fBCGLVector2D\fP*> CGLPolygon::points\fC [protected]\fP"

.PP
Définition à la ligne 23 du fichier CGLPolygon\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
