.TH "CGLPolygon" 3 "Lundi 14 Avril 2014" "Version 20140414" "DGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLPolygon \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Polygon\&.h>\fP
.PP
Est dérivée de CGLItem\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLPolygon\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLPolygon\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "list< \fBCGLVector2D\fP * > \fBpoints\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 20 du fichier Polygon\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLPolygon::CGLPolygon ()"

.PP
Définition à la ligne 10 du fichier Polygon\&.cpp\&.
.SS "CGLPolygon::~CGLPolygon ()\fC [virtual]\fP"

.PP
Définition à la ligne 24 du fichier Polygon\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLPolygon::drawObject (Uint32ellapsedTime)"

.PP
Définition à la ligne 29 du fichier Polygon\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "list<\fBCGLVector2D\fP*> CGLPolygon::points\fC [protected]\fP"

.PP
Définition à la ligne 23 du fichier Polygon\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DGL à partir du code source\&.
