.TH "CGLPosition" 3 "Lundi 14 Avril 2014" "Version 20140414" "DGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLPosition \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Position\&.h>\fP
.PP
Est dérivée de CGLEffect, et CGLVector3D\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLPosition\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLPosition\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.ti -1c
.RI "void \fBsetSpeed\fP (double const sx, double const sy, double const sz)"
.br
.ti -1c
.RI "void \fBsetAccel\fP (double const ax, double const ay, double const az)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "CGLVector3D \fBspeed\fP"
.br
.ti -1c
.RI "CGLVector3D \fBaccel\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 14 du fichier Position\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLPosition::CGLPosition ()"

.PP
Définition à la ligne 10 du fichier Position\&.cpp\&.
.SS "CGLPosition::~CGLPosition ()\fC [virtual]\fP"

.PP
Définition à la ligne 16 du fichier Position\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLPosition::drawObject (Uint32ellapsedTime)"

.PP
Définition à la ligne 30 du fichier Position\&.cpp\&.
.SS "void CGLPosition::setAccel (double constax, double constay, double constaz)"

.PP
Définition à la ligne 25 du fichier Position\&.cpp\&.
.SS "void CGLPosition::setSpeed (double constsx, double constsy, double constsz)"

.PP
Définition à la ligne 20 du fichier Position\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "CGLVector3D CGLPosition::accel\fC [protected]\fP"

.PP
Définition à la ligne 21 du fichier Position\&.h\&.
.SS "CGLVector3D CGLPosition::speed\fC [protected]\fP"

.PP
Définition à la ligne 20 du fichier Position\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DGL à partir du code source\&.
