.TH "CGLPositionSpeedLimited" 3 "Lundi 3 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLPositionSpeedLimited \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLPositionSpeedLimited\&.h>\fP
.PP
Est dérivée de \fBCGLPositionSpeed\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLPositionSpeedLimited\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLPositionSpeedLimited\fP ()"
.br
.ti -1c
.RI "\fBCGLVector3D\fP * \fBgetMin\fP ()"
.br
.ti -1c
.RI "\fBCGLVector3D\fP * \fBgetMax\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBCGLVector3D\fP \fBmin\fP"
.br
.ti -1c
.RI "\fBCGLVector3D\fP \fBmax\fP"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 17 du fichier CGLPositionSpeedLimited\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLPositionSpeedLimited::CGLPositionSpeedLimited ()"

.PP
Définition à la ligne 10 du fichier CGLPositionSpeedLimited\&.cpp\&.
.SS "CGLPositionSpeedLimited::~CGLPositionSpeedLimited ()\fC [virtual]\fP"

.PP
Définition à la ligne 14 du fichier CGLPositionSpeedLimited\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLPositionSpeedLimited::drawObject (Uint32ellapsedTime)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLPositionSpeed\fP\&.
.PP
Définition à la ligne 18 du fichier CGLPositionSpeedLimited\&.cpp\&.
.SS "\fBCGLVector3D\fP * CGLPositionSpeedLimited::getMax ()"

.PP
Définition à la ligne 58 du fichier CGLPositionSpeedLimited\&.cpp\&.
.SS "\fBCGLVector3D\fP * CGLPositionSpeedLimited::getMin ()"

.PP
Définition à la ligne 53 du fichier CGLPositionSpeedLimited\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBCGLVector3D\fP CGLPositionSpeedLimited::max\fC [protected]\fP"

.PP
Définition à la ligne 20 du fichier CGLPositionSpeedLimited\&.h\&.
.SS "\fBCGLVector3D\fP CGLPositionSpeedLimited::min\fC [protected]\fP"

.PP
Définition à la ligne 20 du fichier CGLPositionSpeedLimited\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
