.TH "CGLPosition" 3 "Samedi 1 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLPosition \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLPosition\&.h>\fP
.PP
Est dérivée de \fBCGLEffect\fP, et \fBCGLVector3D\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLPosition\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLPosition\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 14 du fichier CGLPosition\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLPosition::CGLPosition ()"

.PP
Définition à la ligne 10 du fichier CGLPosition\&.cpp\&.
.SS "CGLPosition::~CGLPosition ()\fC [virtual]\fP"

.PP
Définition à la ligne 15 du fichier CGLPosition\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLPosition::drawObject (Uint32ellapsedTime)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 19 du fichier CGLPosition\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
