.TH "CGLQuad" 3 "Lundi 14 Avril 2014" "Version 20140414" "DGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLQuad \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Quad\&.h>\fP
.PP
Est dérivée de CGLItem\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLQuad\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLQuad\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 timeEllapsed)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBCGLVector2D\fP \fBpoints\fP [4]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 14 du fichier Quad\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLQuad::CGLQuad ()"

.PP
Définition à la ligne 10 du fichier Quad\&.cpp\&.
.SS "CGLQuad::~CGLQuad ()\fC [virtual]\fP"

.PP
Définition à la ligne 18 du fichier Quad\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLQuad::drawObject (Uint32timeEllapsed)"

.PP
Définition à la ligne 22 du fichier Quad\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBCGLVector2D\fP CGLQuad::points[4]\fC [protected]\fP"

.PP
Définition à la ligne 19 du fichier Quad\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DGL à partir du code source\&.
