.TH "CGLQuad" 3 "Vendredi 28 Février 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLQuad \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLQuad\&.h>\fP
.PP
Est dérivée de \fBCGLItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLQuad\fP ()"
.br
.ti -1c
.RI "\fBCGLQuad\fP (double x, double y, double z, double r)"
.br
.ti -1c
.RI "virtual \fB~CGLQuad\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 timeEllapsed)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "double \fBlongueur\fP"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 13 du fichier CGLQuad\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLQuad::CGLQuad ()"

.PP
Définition à la ligne 10 du fichier CGLQuad\&.cpp\&.
.SS "CGLQuad::CGLQuad (doublex, doubley, doublez, doubler)"

.PP
Définition à la ligne 16 du fichier CGLQuad\&.cpp\&.
.SS "CGLQuad::~CGLQuad ()\fC [virtual]\fP"

.PP
Définition à la ligne 21 du fichier CGLQuad\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLQuad::drawObject (Uint32timeEllapsed)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 25 du fichier CGLQuad\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "double CGLQuad::longueur\fC [protected]\fP"

.PP
Définition à la ligne 18 du fichier CGLQuad\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
