.TH "CGLQuad" 3 "Lundi 3 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLQuad \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLQuad\&.h>\fP
.PP
Est dérivée de \fBCGLItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLQuad\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLQuad\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 timeEllapsed)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBCGLVector2D\fP \fBpoints\fP [4]"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 14 du fichier CGLQuad\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLQuad::CGLQuad ()"

.PP
Définition à la ligne 10 du fichier CGLQuad\&.cpp\&.
.SS "CGLQuad::~CGLQuad ()\fC [virtual]\fP"

.PP
Définition à la ligne 18 du fichier CGLQuad\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLQuad::drawObject (Uint32timeEllapsed)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 22 du fichier CGLQuad\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBCGLVector2D\fP CGLQuad::points[4]\fC [protected]\fP"

.PP
Définition à la ligne 19 du fichier CGLQuad\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
