.TH "CGLRobot1" 3 "Lundi 14 Avril 2014" "Version 20140414" "DGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLRobot1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Robot1\&.h>\fP
.PP
Est dérivée de CGLItem\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLRobot1\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLRobot1\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 timeEllapsed)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 13 du fichier Robot1\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLRobot1::CGLRobot1 ()"

.PP
Définition à la ligne 10 du fichier Robot1\&.cpp\&.
.SS "CGLRobot1::~CGLRobot1 ()\fC [virtual]\fP"

.PP
Définition à la ligne 26 du fichier Robot1\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLRobot1::drawObject (Uint32timeEllapsed)"

.PP
Définition à la ligne 30 du fichier Robot1\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DGL à partir du code source\&.
