.TH "CGLRotation" 3 "Vendredi 28 Février 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLRotation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLRotation\&.h>\fP
.PP
Est dérivée de \fBCGLEffect\fP, et \fBCGLVector3D\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLRotation\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLRotation\fP ()"
.br
.ti -1c
.RI "void \fBsetA\fP (double av)"
.br
.ti -1c
.RI "double \fBgetA\fP ()"
.br
.ti -1c
.RI "void \fBset\fP (double av, double ax, double ay, double az)"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 16 du fichier CGLRotation\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLRotation::CGLRotation ()"

.PP
Définition à la ligne 10 du fichier CGLRotation\&.cpp\&.
.SS "CGLRotation::~CGLRotation ()\fC [virtual]\fP"

.PP
Définition à la ligne 16 du fichier CGLRotation\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLRotation::drawObject (Uint32ellapsedTime)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 38 du fichier CGLRotation\&.cpp\&.
.SS "double CGLRotation::getA ()"

.PP
Définition à la ligne 25 du fichier CGLRotation\&.cpp\&.
.SS "void CGLRotation::set (doubleav, doubleax, doubleay, doubleaz)"

.PP
Définition à la ligne 30 du fichier CGLRotation\&.cpp\&.
.SS "void CGLRotation::setA (doubleav)"

.PP
Définition à la ligne 20 du fichier CGLRotation\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
