.TH "CGLRobot1" 3 "Samedi 1 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLRobot1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLRobot1\&.h>\fP
.PP
Est dérivée de \fBCGLItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLRobot1\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLRobot1\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 timeEllapsed)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 13 du fichier CGLRobot1\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLRobot1::CGLRobot1 ()"

.PP
Définition à la ligne 10 du fichier CGLRobot1\&.cpp\&.
.SS "CGLRobot1::~CGLRobot1 ()\fC [virtual]\fP"

.PP
Définition à la ligne 26 du fichier CGLRobot1\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLRobot1::drawObject (Uint32timeEllapsed)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 30 du fichier CGLRobot1\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
