.TH "CGLRotation" 3 "Lundi 14 Avril 2014" "Version 20140414" "DGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLRotation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Rotation\&.h>\fP
.PP
Est dérivée de CGLEffect, et CGLVector3D\&.
.PP
Dérivée par \fBCGLRotationSpeed\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLRotation\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLRotation\fP ()"
.br
.ti -1c
.RI "void \fBsetA\fP (double av)"
.br
.ti -1c
.RI "double \fBgetA\fP ()"
.br
.ti -1c
.RI "void \fBset\fP (double av, double ax, double ay, double az)"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "double \fBa\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 17 du fichier Rotation\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLRotation::CGLRotation ()"

.PP
Définition à la ligne 10 du fichier Rotation\&.cpp\&.
.SS "CGLRotation::~CGLRotation ()\fC [virtual]\fP"

.PP
Définition à la ligne 16 du fichier Rotation\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLRotation::drawObject (Uint32ellapsedTime)"

.PP
Définition à la ligne 38 du fichier Rotation\&.cpp\&.
.SS "double CGLRotation::getA ()"

.PP
Définition à la ligne 25 du fichier Rotation\&.cpp\&.
.SS "void CGLRotation::set (doubleav, doubleax, doubleay, doubleaz)"

.PP
Définition à la ligne 30 du fichier Rotation\&.cpp\&.
.SS "void CGLRotation::setA (doubleav)"

.PP
Définition à la ligne 20 du fichier Rotation\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "double CGLRotation::a\fC [protected]\fP"

.PP
Définition à la ligne 20 du fichier Rotation\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DGL à partir du code source\&.
