.TH "CGLRotationSpeed" 3 "Lundi 3 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLRotationSpeed \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLRotationSpeed\&.h>\fP
.PP
Est dérivée de \fBCGLRotation\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLRotationSpeed\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLRotationSpeed\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "double \fBspeed\fP"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 17 du fichier CGLRotationSpeed\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLRotationSpeed::CGLRotationSpeed ()"

.PP
Définition à la ligne 10 du fichier CGLRotationSpeed\&.cpp\&.
.SS "CGLRotationSpeed::~CGLRotationSpeed ()\fC [virtual]\fP"

.PP
Définition à la ligne 14 du fichier CGLRotationSpeed\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLRotationSpeed::drawObject (Uint32ellapsedTime)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLRotation\fP\&.
.PP
Définition à la ligne 18 du fichier CGLRotationSpeed\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "double CGLRotationSpeed::speed\fC [protected]\fP"

.PP
Définition à la ligne 20 du fichier CGLRotationSpeed\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
