.TH "CGLScale" 3 "Dimanche 2 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLScale \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLScale\&.h>\fP
.PP
Est dérivée de \fBCGLEffect\fP, et \fBCGLVector3D\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLScale\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLScale\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 17 du fichier CGLScale\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLScale::CGLScale ()"

.PP
Définition à la ligne 10 du fichier CGLScale\&.cpp\&.
.SS "CGLScale::~CGLScale ()\fC [virtual]\fP"

.PP
Définition à la ligne 15 du fichier CGLScale\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLScale::drawObject (Uint32ellapsedTime)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 19 du fichier CGLScale\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
