.TH "CGLSpecial" 3 "Vendredi 28 Février 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLSpecial \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLSpecial\&.h>\fP
.PP
Est dérivée de \fBCGLObject\fP\&.
.PP
Dérivée par \fBCGLCamera\fP, \fBCGLCameraList\fP, \fBCGLLight\fP, \fBCGLScene\fP, \fBCGLWindow\fP, et \fBCGLWorld\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLSpecial\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLSpecial\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 17 du fichier CGLSpecial\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLSpecial::CGLSpecial ()"

.PP
Définition à la ligne 10 du fichier CGLSpecial\&.cpp\&.
.SS "CGLSpecial::~CGLSpecial ()\fC [virtual]\fP"

.PP
Définition à la ligne 15 du fichier CGLSpecial\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
