.TH "CGLScale" 3 "Lundi 14 Avril 2014" "Version 20140414" "DGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLScale \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scale\&.h>\fP
.PP
Est dérivée de CGLEffect, et CGLVector3D\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLScale\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLScale\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 17 du fichier Scale\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLScale::CGLScale ()"

.PP
Définition à la ligne 10 du fichier Scale\&.cpp\&.
.SS "CGLScale::~CGLScale ()\fC [virtual]\fP"

.PP
Définition à la ligne 15 du fichier Scale\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLScale::drawObject (Uint32ellapsedTime)"

.PP
Définition à la ligne 19 du fichier Scale\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DGL à partir du code source\&.
