.TH "CGLTriangle" 3 "Lundi 14 Avril 2014" "Version 20140414" "DGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLTriangle \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Triangle\&.h>\fP
.PP
Est dérivée de CGLItem\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLTriangle\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLTriangle\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBCGLVector2D\fP \fBpoints\fP [3]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 18 du fichier Triangle\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLTriangle::CGLTriangle ()"

.PP
Définition à la ligne 10 du fichier Triangle\&.cpp\&.
.SS "CGLTriangle::~CGLTriangle ()\fC [virtual]\fP"

.PP
Définition à la ligne 17 du fichier Triangle\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLTriangle::drawObject (Uint32ellapsedTime)"

.PP
Définition à la ligne 21 du fichier Triangle\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBCGLVector2D\fP CGLTriangle::points[3]\fC [protected]\fP"

.PP
Définition à la ligne 21 du fichier Triangle\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DGL à partir du code source\&.
