.TH "CGLTriangle" 3 "Dimanche 2 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLTriangle \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLTriangle\&.h>\fP
.PP
Est dérivée de \fBCGLItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLTriangle\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLTriangle\fP ()"
.br
.ti -1c
.RI "void \fBdrawObject\fP (Uint32 ellapsedTime)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBCGLVector2D\fP \fBpoints\fP [3]"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 18 du fichier CGLTriangle\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLTriangle::CGLTriangle ()"

.PP
Définition à la ligne 10 du fichier CGLTriangle\&.cpp\&.
.SS "CGLTriangle::~CGLTriangle ()\fC [virtual]\fP"

.PP
Définition à la ligne 17 du fichier CGLTriangle\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLTriangle::drawObject (Uint32ellapsedTime)\fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBCGLObject\fP\&.
.PP
Définition à la ligne 21 du fichier CGLTriangle\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBCGLVector2D\fP CGLTriangle::points[3]\fC [protected]\fP"

.PP
Définition à la ligne 21 du fichier CGLTriangle\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
