.TH "CGLVector4D" 3 "Samedi 1 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLVector4D \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLVector4D\&.h>\fP
.PP
Est dérivée de \fBCGLVector3D\fP\&.
.PP
Dérivée par \fBCGLColor\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLVector4D\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLVector4D\fP ()"
.br
.ti -1c
.RI "double \fBgetW\fP ()"
.br
.ti -1c
.RI "void \fBsetW\fP (double val)"
.br
.ti -1c
.RI "void \fBset\fP (double vx, double vy, double vz, double vw)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "double \fBw\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 16 du fichier CGLVector4D\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLVector4D::CGLVector4D ()"

.PP
Définition à la ligne 10 du fichier CGLVector4D\&.cpp\&.
.SS "CGLVector4D::~CGLVector4D ()\fC [virtual]\fP"

.PP
Définition à la ligne 15 du fichier CGLVector4D\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "double CGLVector4D::getW ()"

.PP
Définition à la ligne 19 du fichier CGLVector4D\&.cpp\&.
.SS "void CGLVector4D::set (doublevx, doublevy, doublevz, doublevw)"

.PP
Définition à la ligne 29 du fichier CGLVector4D\&.cpp\&.
.SS "void CGLVector4D::setW (doubleval)"

.PP
Définition à la ligne 24 du fichier CGLVector4D\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "double CGLVector4D::w\fC [protected]\fP"

.PP
Définition à la ligne 19 du fichier CGLVector4D\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
