.TH "CGLVector3D" 3 "Dimanche 2 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLVector3D \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLVector3D\&.h>\fP
.PP
Est dérivée de \fBCGLVector2D\fP\&.
.PP
Dérivée par \fBCGLPosition\fP, \fBCGLRotation\fP, \fBCGLScale\fP, et \fBCGLVector4D\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLVector3D\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLVector3D\fP ()"
.br
.ti -1c
.RI "bool \fBisEqualTo\fP (\fBCGLVector3D\fP const &b) const "
.br
.ti -1c
.RI "double const & \fBgetZ\fP () const "
.br
.ti -1c
.RI "void \fBset\fP (double const &xv, double const &yv, double const &zv)"
.br
.ti -1c
.RI "void \fBsetZ\fP (double const &val)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "double \fBz\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 14 du fichier CGLVector3D\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLVector3D::CGLVector3D ()"

.PP
Définition à la ligne 10 du fichier CGLVector3D\&.cpp\&.
.SS "CGLVector3D::~CGLVector3D ()\fC [virtual]\fP"

.PP
Définition à la ligne 15 du fichier CGLVector3D\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "double const & CGLVector3D::getZ () const"

.PP
Définition à la ligne 18 du fichier CGLVector3D\&.cpp\&.
.SS "bool CGLVector3D::isEqualTo (\fBCGLVector3D\fP const &b) const"

.PP
Définition à la ligne 35 du fichier CGLVector3D\&.cpp\&.
.SS "void CGLVector3D::set (double const &xv, double const &yv, double const &zv)"

.PP
Définition à la ligne 23 du fichier CGLVector3D\&.cpp\&.
.SS "void CGLVector3D::setZ (double const &val)"

.PP
Définition à la ligne 30 du fichier CGLVector3D\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "double CGLVector3D::z\fC [protected]\fP"

.PP
Définition à la ligne 20 du fichier CGLVector3D\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
