.TH "CGLWorld" 3 "Jeudi 6 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLWorld \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLWorld\&.h>\fP
.PP
Est dérivée de \fBCGLSpecial\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLWorld\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLWorld\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP (Uint32 timeEllapsed)"
.br
.ti -1c
.RI "\fBCGLScene\fP * \fBgetCurrentScene\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 13 du fichier CGLWorld\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLWorld::CGLWorld ()"

.PP
Définition à la ligne 10 du fichier CGLWorld\&.cpp\&.
.SS "CGLWorld::~CGLWorld ()\fC [virtual]\fP"

.PP
Définition à la ligne 20 du fichier CGLWorld\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLWorld::draw (Uint32timeEllapsed)"

.PP
Définition à la ligne 23 du fichier CGLWorld\&.cpp\&.
.SS "\fBCGLScene\fP * CGLWorld::getCurrentScene ()"

.PP
Définition à la ligne 29 du fichier CGLWorld\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
