.TH "CGLWindow" 3 "Samedi 1 Mars 2014" "Version 20140227" "DamierGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CGLWindow\&.h>\fP
.PP
Est dérivée de \fBCGLSpecial\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCGLWindow\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGLWindow\fP ()"
.br
.ti -1c
.RI "void \fBloop\fP ()"
.br
.ti -1c
.RI "void \fBexec\fP ()"
.br
.ti -1c
.RI "void \fBonResize\fP (SDL_Event &ev)"
.br
.ti -1c
.RI "void \fBdraw\fP (Uint32 ellapsedTime)"
.br
.ti -1c
.RI "\fBCGLWorld\fP * \fBgetCurrentWorld\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 16 du fichier CGLWindow\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CGLWindow::CGLWindow ()"

.PP
Définition à la ligne 10 du fichier CGLWindow\&.cpp\&.
.SS "CGLWindow::~CGLWindow ()\fC [virtual]\fP"

.PP
Définition à la ligne 26 du fichier CGLWindow\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "void CGLWindow::draw (Uint32ellapsedTime)"

.PP
Définition à la ligne 80 du fichier CGLWindow\&.cpp\&.
.SS "void CGLWindow::exec ()"

.PP
Définition à la ligne 87 du fichier CGLWindow\&.cpp\&.
.SS "\fBCGLWorld\fP * CGLWindow::getCurrentWorld ()"

.PP
Définition à la ligne 129 du fichier CGLWindow\&.cpp\&.
.SS "void CGLWindow::loop ()"

.PP
Définition à la ligne 32 du fichier CGLWindow\&.cpp\&.
.SS "void CGLWindow::onResize (SDL_Event &ev)"

.PP
Définition à la ligne 118 du fichier CGLWindow\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DamierGL à partir du code source\&.
