.TH "/home/dagal/git/DGL/DamierGL/src/DamierGL.cpp" 3 "Lundi 14 Avril 2014" "Version 20140414" "DGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dagal/git/DGL/DamierGL/src/DamierGL.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CGL/Window\&.h'\fP
.br
\fC#include 'CGL/CGLQuad\&.h'\fP
.br
\fC#include 'CGL/CGLRobot1\&.h'\fP
.br
\fC#include 'CGL/CGLColor\&.h'\fP
.br
\fC#include 'CGL/CGLScale\&.h'\fP
.br
\fC#include 'CGL/CGLDot\&.h'\fP
.br
\fC#include 'CGL/CGLLine\&.h'\fP
.br
\fC#include 'CGL/CGLTriangle\&.h'\fP
.br
\fC#include 'CGL/CGLPolygon\&.h'\fP
.br
\fC#include 'CGL/CGLCircle\&.h'\fP
.br
\fC#include 'CGL/CGLPosition\&.h'\fP
.br
\fC#include 'CGL/CGLRotationSpeed\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Définition à la ligne 24 du fichier DamierGL\&.cpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DGL à partir du code source\&.
