.TH "src/DamierGL.cpp" 3 "Mardi 15 Avril 2014" "Version 20140414" "DGL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/DamierGL.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CGL/Window\&.h'\fP
.br
\fC#include 'CGL/Quad\&.h'\fP
.br
\fC#include 'CGL/Robot1\&.h'\fP
.br
\fC#include 'CGL/Color\&.h'\fP
.br
\fC#include 'CGL/Scale\&.h'\fP
.br
\fC#include 'CGL/Dot\&.h'\fP
.br
\fC#include 'CGL/Line\&.h'\fP
.br
\fC#include 'CGL/Triangle\&.h'\fP
.br
\fC#include 'CGL/Polygon\&.h'\fP
.br
\fC#include 'CGL/Circle\&.h'\fP
.br
\fC#include 'CGL/Position\&.h'\fP
.br
\fC#include 'CGL/RotationSpeed\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Définition à la ligne 24 du fichier DamierGL\&.cpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DGL à partir du code source\&.
